name: Frontend CD

on:
  # Condición: Disparo manual
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Necesitamos permisos de escritura para publicar en el registro de paquetes
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Autenticación en GitHub Container Registry (GHCR)
      # Usamos el GITHUB_TOKEN que se crea automáticamente para el workflow
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2. Extraer metadatos para Docker (etiquetas y nombres)
      # Esto ayuda a gestionar versiones de forma automática
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/hangman-front
          tags: |
            type=raw,value=latest

      # 3. Construir y publicar la imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./hangman-front
          push: true
          # Usamos los tags generados en el paso anterior
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
